export const ROUTES = {
  home: "/",

  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  freightOwner: "/freight-owner",
  freightOwnerLoads: "/freight-owner/loads",
  freightOwnerNewLoad: "/freight-owner/loads/new",
  freightOwnerMatches: "/freight-owner/matches",
  freightOwnerReceipts: "/freight-owner/receipts",
  freightOwnerTracking: "/freight-owner/tracking",
  freightOwnerRatings: "/freight-owner/ratings",
  freightOwnerSettings: "/freight-owner/settings",
  transporter: "/transporter",
  transporterTrucks: "/transporter/trucks",
  transporterNewTruck: "/transporter/trucks/new",
  transporterEditTruck: "/transporter/trucks/:truckId/edit",
  transporterMatches: "/transporter/matches",
  admin: "/admin",
} as const;
